
name: "Terraform Deployment APPLY"

on: [push]
  # workflow_dispatch:
  # push:
  #   paths:
  #     - '/*'
  # pull_request:
  #   branches: [main]

jobs:
  terraform:
    name:   ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on:  '${{ matrix.runner }}'
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: sandbox
             runner: ubuntu-latest
          #  - environment: dev
          #    runner: ubuntu-18.04             

    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 1.1.5
          args: '-var-file="${{ matrix.environment}}.tfvars"'
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
          
    - name: Terraform Init
      id: init
      run: |
        terraform init -upgrade=true -no-color -input=false  
        
    - name: Terraform Create Workspace
      id: Workspace
      run: |
        terraform workspace new ${{ matrix.environment }} || terraform workspace select ${{ matrix.environment }}
      continue-on-error: true   

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var-file="${{ matrix.environment }}.tfvars"  -out="plan.${{ matrix.environment }}" -no-color 
      continue-on-error: true  

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' 
      id: Apply
      run: |
        terraform apply "plan.${{ matrix.environment }}"    

  comment:
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })